### ISSUE TITLE
Do not overwrite existing output files

### ISSUE THREAD

**Issue by SpotlightKid** [prusnak/micropython-extmod-generator#3]
Because manual edits might be lost.

Maybe provide an `-f` (force overwrite) command line option.

**Comment by prusnak** [comment]
Sounds OK. Can you prepare a pull request?

## 

Best Regards / S pozdravom,

Pavol Rusnak stick@gk2.sk

On Fri, Mar 4, 2016, at 02:42 PM, Christopher Arndt wrote:

> Because manual edits might be lost.
> 
> Maybe provide an -f (force overwrite) command line option.
> 
> —
> Reply to this email directly or view it on GitHub[1]. 

Links:
1. https://github.com/prusnak/micropython-extmod-generator/issues/3

**Comment by SpotlightKid** [comment]
Ok, I'll look into it later tonight.
